spring:
  application:
    name: expenses-control
  datasource:
    url: jdbc:postgresql://localhost:5432/expensescontrol
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect