spring:
  application:
    name: expenses-control
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/expensescontrol
    username: ${DB_USER:postgres}
    password: ${DB_PASS:docker}
    driver-class-name: org.postgresql.Driver
    maxActive: 3
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect